### ISSUE TITLE
Este é o erro 

### ISSUE THREAD

**Issue by thelilburna** [rafegal/sos_pet#4]
File "C:\Users\aluno\Documents\GitHub\sospet2\sos_pet-master\sos_pet\settings.py", line 14, in <module>
    import dj_database_url
ModuleNotFoundError: No module named 'dj_database_url'

**Comment by rafegal** [comment]
Você instalou as dependências que estão no arquivo requirements.txt? O "dj_database_url" é um dependência do projeto que já consta no arquivo de dependência.
